#OBJS specifies which files to compile as part of the project
#OBJS=01_hello_SDL.cpp

#OBJ_NAME specifies the name of our exectuable
#OBJ_NAME=01_hello_SDL

#This is the target that compiles our executable
#all : 01_hello_SDL.cpp
g++ 01_hello_SDL.cpp -w -lSDL2 -o 01_hello_SDL
